### ISSUE TITLE
the day care freezes the game after index 898 because the structure for international text overflows

### ISSUE THREAD

**Issue by Bubble791** [BluRosie/hgss-monexpansion#4] opened 2021-05-27 05:46 UTC

**Comment by BluRosie** [comment] 2021-06-02 12:58
this is likely caused by the save file not actually being dynamically allocated as the [code written](https://github.com/BluRosie/hgss-monexpansion/blob/gen5/asm/pokedex.s#L977) assumes.  the pokemon in the daycare is thus read from the dex data, specifically the gender flags at the end of the structure.  hopefully an easy fix!

**Comment by BluRosie** [comment] 2021-06-04 02:44
[can not reproduce](https://cdn.discordapp.com/attachments/742361100389187666/850202894165999616/unknown.png), if when adding more pokemon later it becomes an issue then i will reopen the issue and go from there

**Comment by BluRosie** [comment] 2021-06-04 05:36
need to take out the international dex pages in order to get this to work properly.  basically it overflows the area, so i can either take the system out or expand it.  taking it out is far preferable

**Comment by BluRosie** [comment] 2021-08-13 18:42
closing because it won't be an issue for a bit--just have to expand the dex structure when we get there so it malloc's more space (maybe to 0x4C0 instead)

**Closed as completed by BluRosie** 2021-08-13 18:42 UTC
Labels: bug
